#!/usr/bin/env python3
"""Build pinned MXCoreFP4 RTL, check all 54 shapes, and export measured profiles."""
import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import subprocess

from reference import SHAPES, make_case
from rtl.prepare import REVISION, prepare

HERE = Path(__file__).resolve().parent
MODEL = HERE.parents[1] / 'pulp' / 'mxcore_fp4'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def build(args):
    rtl, work = args.rtl, args.work
    if args.fetch:
        if not rtl.exists():
            subprocess.run(['git', 'clone', 'https://github.com/pulp-platform/MXCore.git', str(rtl)], check=True)
        subprocess.run(['git', 'checkout', '--detach', REVISION], cwd=rtl, check=True)
        subprocess.run(shlex.split(args.bender) + ['checkout'], cwd=rtl, check=True)
    prepare(rtl)
    sources = subprocess.check_output(shlex.split(args.bender) +
              ['script', 'verilator', '-t', 'rtl', '-t', 'mxcore_hwpe'], cwd=rtl, text=True)
    for key, value in [('VECTOR_SIZE',16), ('NPE',32), ('REUSE',32), ('NUM_PIPE_REGS',4), ('TCDM_BW',256)]:
        sources = re.sub(rf'\+define\+{key}=\d+', f'+define+{key}={value}', sources)
    (work/'sources.f').write_text(sources)
    command = shlex.split(args.verilator) + [
        '--cc', '--exe', '--build', '-j', str(args.jobs), '--Mdir', str(work/'obj'),
        '--top-module', 'mxcore_hwpe_wrap', '-Wno-fatal', '-Wno-BLKANDNBLK', '--no-timing',
        '-f', str(work/'sources.f'), str(HERE/'rtl/mxcore_fp4_quantizer.sv'), str(HERE/'rtl/driver.cpp')]
    env = dict(os.environ, CCACHE_DIR=str(work/'ccache'))
    with (work/'build.log').open('w') as log:
        subprocess.run(command, cwd=rtl, stdout=log, stderr=subprocess.STDOUT, env=env, check=True)


def sweep(args):
    work=args.work
    executable=args.executable or work/'obj/Vmxcore_hwpe_wrap'
    records, words, profiles = [], [], []
    for m,n,k in SHAPES:
        name=f'm{m}_n{n}_k{k}'
        expected_trace=None
        for seed in args.seeds:
            memory, golden=make_case(m,n,k,seed)
            (work/'memory.bin').write_bytes(memory)
            result=subprocess.run([str(executable),str(m),str(n),str(k),str(work/'memory.bin'),
                                   str(work/'output.bin'),str(work/'trace.csv')],
                                  check=True, capture_output=True, text=True, timeout=60)
            (work/f'{name}_seed{seed}.log').write_text(result.stdout+result.stderr)
            match=re.search(r'MXCORE_RTL,\d+,\d+,\d+,(\d+)',result.stdout)
            if not match:
                raise RuntimeError(f'{name}: missing RTL completion marker')
            actual=(work/'output.bin').read_bytes()
            if actual!=golden:
                bad=[i for i,(x,y) in enumerate(zip(actual,golden)) if x!=y]
                raise RuntimeError(f'{name} seed {seed}: {len(bad)} mismatches, first {bad[:8]}, lengths {len(actual)}/{len(golden)}')
            trace=(work/'trace.csv').read_text()
            cycles=int(match[1])
            if expected_trace is not None and (trace!=expected_trace or cycles!=expected_cycles):
                raise RuntimeError(f'{name}: data-dependent RTL timing')
            expected_trace, expected_cycles=trace,cycles
            records.append(dict(m=m,n=n,k=k,seed=seed,rtl_cycles=cycles,
                                input_sha256=sha(memory),output_sha256=sha(actual),
                                trace_sha256=sha(trace.encode()), mismatched_bytes=0))
        transactions=[tuple(map(int,line.split(','))) for line in trace.splitlines()]
        start=len(words); previous=0
        for cycle,region,offset in transactions:
            if not (0<cycle-previous<65536 and 0<=region<6 and offset%32==0 and offset//32<8192):
                raise RuntimeError(f'{name}: invalid transaction {cycle,region,offset}')
            words.append(((cycle-previous)<<16)|(region<<13)|(offset//32))
            previous=cycle
        profiles.append((m,n,k,cycles,start,len(transactions)))
        (work/f'{name}.csv').write_text(trace)
        # Inputs and the verified RTL result are reused by the GVSoC test.
        (work/f'{name}.bin').write_bytes(memory)
        (work/f'{name}.expected').write_bytes(actual)
        print(f'{name}: {cycles} cycles, {len(transactions)} transfers, {len(args.seeds)} seeds passed',flush=True)

    body='// Generated by pulp/tests/mxcore_fp4/calibrate.py. Do not edit.\n'
    body+='inline constexpr uint32_t transfers[] = {\n'
    body+=''.join('    '+','.join(f'0x{v:08x}' for v in words[i:i+8])+',\n' for i in range(0,len(words),8))
    body+='};\ninline constexpr Profile profiles[] = {\n'
    body+=''.join('    {'+','.join(map(str,p))+'},\n' for p in profiles)
    body+='};\n'
    # Exercise numerical cases beyond the moderate scales in the timing sweep.
    cpp=work/'compute'
    subprocess.run(shlex.split(args.cxx)+['-std=c++17','-O2',str(HERE/'compute_cli.cpp'),'-o',str(cpp)],check=True)
    directed=[]
    for pattern in ('zero','ones','ties','wide','tiny','scale_nan'):
        memory,golden=make_case(32,32,192,42,pattern)
        (work/'memory.bin').write_bytes(memory)
        result=subprocess.run([str(executable),'32','32','192',str(work/'memory.bin'),
                               str(work/'output.bin'),str(work/'trace.csv')],
                              check=True,capture_output=True,text=True,timeout=60)
        subprocess.run([str(cpp),'32','32','192',str(work/'memory.bin'),str(work/'compute.bin')],check=True)
        if (work/'output.bin').read_bytes()!=golden or (work/'compute.bin').read_bytes()!=golden:
            raise RuntimeError(f'Directed numerical test failed: {pattern}')
        directed.append(dict(pattern=pattern,m=32,n=32,k=192,seed=42,mismatched_bytes=0,
                             input_sha256=sha(memory),output_sha256=sha(golden)))
        (work/f'directed_{pattern}.log').write_text(result.stdout+result.stderr)
        print(f'directed {pattern}: RTL, Python, and C++ agree',flush=True)
    # Keep the exact source changes reviewable, including the dependency fix.
    upstream_patch=subprocess.check_output(['git','diff','--','mxcore-rtl'],cwd=args.rtl)
    fpnew=next(args.rtl.glob('.bender/git/checkouts/fpnew-*/src/mxdotp/fpnew_mxdotp_multi_modules.sv')).parents[2]
    fpnew_patch=subprocess.check_output(['git','diff'],cwd=fpnew)
    actual_revision=subprocess.check_output(['git','rev-parse','HEAD'],cwd=args.rtl,text=True).strip()
    if actual_revision!=REVISION: raise RuntimeError('Unexpected RTL revision')
    report=dict(upstream_url='https://github.com/pulp-platform/MXCore',upstream_revision=actual_revision,
        generated_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        hardware=dict(vector_size=16,fp4_values_per_dot=32,npe=32,reuse=32,num_pipe_regs=4,
                      tcdm_bits=256,input_block_size=32,output_block_size=32,memory_read_latency=1),
        scope='Patched MXCoreFP4 HWPE; trigger acceptance edge to completion event; no memory stalls.',
        profiles_sha256=sha(body.encode()), quantizer_sha256=sha((HERE/'rtl/mxcore_fp4_quantizer.sv').read_bytes()),
        driver_sha256=sha((HERE/'rtl/driver.cpp').read_bytes()),
        reference_sha256=sha((HERE/'reference.py').read_bytes()),
        dependency_lock_sha256=sha((args.rtl/'Bender.lock').read_bytes()),
        upstream_patch_sha256=sha(upstream_patch),fpnew_patch_sha256=sha(fpnew_patch),
        verilator=subprocess.check_output(shlex.split(args.verilator)+['--version'],text=True).strip(),
        bender=subprocess.check_output(shlex.split(args.bender)+['--version'],text=True).strip(),
        records=records,directed=directed)
    (work/'profiles.inc').write_text(body)
    (work/'calibration.json').write_text(json.dumps(report,indent=2)+'\n')
    if args.export:
        (MODEL/'profiles.inc').write_text(body)
        (HERE/'calibration.json').write_text(json.dumps(report,indent=2)+'\n')
        (HERE/'rtl/mxcore.patch').write_bytes(upstream_patch)
        (HERE/'rtl/fpnew.patch').write_bytes(fpnew_patch)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--rtl',type=Path,default=HERE/'build/MXCore')
    parser.add_argument('--work',type=Path,default=HERE/'build/calibration')
    parser.add_argument('--bender',default='bender-0.28.1')
    parser.add_argument('--verilator',default='verilator')
    parser.add_argument('--jobs',type=int,default=8)
    parser.add_argument('--cxx',default=os.environ.get('CXX','c++'))
    parser.add_argument('--fetch',action='store_true')
    parser.add_argument('--skip-build',action='store_true')
    parser.add_argument('--executable',type=Path)
    parser.add_argument('--seeds',type=int,nargs='+',default=[1,7])
    parser.add_argument('--export',action='store_true',help='Replace checked-in profiles only after every case passes')
    args=parser.parse_args()
    args.rtl=args.rtl.resolve(); args.work=args.work.resolve(); args.work.mkdir(parents=True,exist_ok=True)
    if args.executable: args.executable=args.executable.resolve()
    if not args.skip_build: build(args)
    sweep(args)
